# Generated by Django 5.2.8 on 2026-02-07 21:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reference_number", models.CharField(db_index=True, max_length=100)),
                (
                    "waybill_number",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                (
                    "tracking_number",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                (
                    "courier_provider",
                    models.CharField(
                        choices=[
                            ("SMSA", "SMSA"),
                            ("ARAMEX", "ARAMEX"),
                            ("MOCK", "MOCK"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "PENDING"),
                            ("CREATED", "CREATED"),
                            ("CONFIRMED", "CONFIRMED"),
                            ("PICKED_UP", "PICKED_UP"),
                            ("IN_TRANSIT", "IN_TRANSIT"),
                            ("OUT_FOR_DELIVERY", "OUT_FOR_DELIVERY"),
                            ("DELIVERED", "DELIVERED"),
                            ("FAILED_DELIVERY", "FAILED_DELIVERY"),
                            ("RETURNED", "RETURNED"),
                            ("CANCELLED", "CANCELLED"),
                            ("EXCEPTION", "EXCEPTION"),
                            ("LOST", "LOST"),
                            ("DAMAGED", "DAMAGED"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=50,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("STANDARD", "STANDARD"),
                            ("EXPRESS", "EXPRESS"),
                            ("PRIORITY", "PRIORITY"),
                        ],
                        default="STANDARD",
                        max_length=20,
                    ),
                ),
                ("sender_data", models.JSONField(default=dict)),
                ("recipient_data", models.JSONField(default=dict)),
                ("package_data", models.JSONField(default=dict)),
                ("courier_specific_data", models.JSONField(blank=True, default=dict)),
                ("service_type", models.CharField(blank=True, max_length=50)),
                ("special_instructions", models.TextField(blank=True)),
                (
                    "cod_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("cod_currency", models.CharField(default="SAR", max_length=3)),
                (
                    "insurance_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "estimated_delivery_date",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("actual_delivery_date", models.DateTimeField(blank=True, null=True)),
                (
                    "cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("currency", models.CharField(default="SAR", max_length=3)),
                ("label_url", models.URLField(blank=True)),
                ("label_data", models.TextField(blank=True)),
                ("last_status_update", models.DateTimeField(auto_now=True)),
                ("last_status_description", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["courier_provider", "status"],
                        name="core_shipme_courier_6e4fcb_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="core_shipme_created_3091b3_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TrackingEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "PENDING"),
                            ("CREATED", "CREATED"),
                            ("CONFIRMED", "CONFIRMED"),
                            ("PICKED_UP", "PICKED_UP"),
                            ("IN_TRANSIT", "IN_TRANSIT"),
                            ("OUT_FOR_DELIVERY", "OUT_FOR_DELIVERY"),
                            ("DELIVERED", "DELIVERED"),
                            ("FAILED_DELIVERY", "FAILED_DELIVERY"),
                            ("RETURNED", "RETURNED"),
                            ("CANCELLED", "CANCELLED"),
                            ("EXCEPTION", "EXCEPTION"),
                            ("LOST", "LOST"),
                            ("DAMAGED", "DAMAGED"),
                        ],
                        max_length=50,
                    ),
                ),
                ("raw_status", models.CharField(blank=True, max_length=100)),
                ("description", models.TextField()),
                ("location", models.CharField(blank=True, max_length=200)),
                ("details", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "shipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracking_events",
                        to="core.shipment",
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp"],
                "indexes": [
                    models.Index(
                        fields=["shipment", "timestamp"],
                        name="core_tracki_shipmen_60ecd5_idx",
                    )
                ],
            },
        ),
    ]
